version: "3.8"

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/testeb/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test-eb-p
      - POSTGRES_PASSWORD=test-eb-p
      - POSTGRES_DB=test-eb-p_dev

volumes:
  postgres_data: