version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: 249128845279.dkr.ecr.us-east-2.amazonaws.com/test-eb:web
    command: gunicorn testeb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/testeb/web/staticfiles
      - media_volume:/home/testeb/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
  
  nginx:
    build: ./nginx
    image: 249128845279.dkr.ecr.us-east-2.amazonaws.com/test-eb:nginx
    volumes:
      - static_volume:/home/testeb/web/staticfiles
      - media_volume:/home/testeb/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: